# Generated by Django 4.2.4 on 2023-09-04 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_userorder_alter_orderitem_order_delete_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUserForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('delivery', models.CharField(choices=[('delivery', 'delivery'), ('pickup', 'pickup')], max_length=64)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registered_user_form', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
