# Generated by Django 4.2.4 on 2023-09-04 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_registereduserform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredUserForm',
            new_name='UserData',
        ),
    ]
