# Generated by Django 4.2.4 on 2023-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_registereduserform_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
