# Generated by Django 4.2.4 on 2023-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_userdata_address_alter_userdata_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('in process', 'in process'), ('active', 'active'), ('processed', 'processed'), ('canceled', 'canceled')], default='canceled', max_length=60),
        ),
    ]
