# Generated by Django 4.2.4 on 2023-08-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='product/'),
        ),
    ]
