# Generated by Django 4.2.4 on 2023-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_category_creator_product_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descr',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
